export const ErrorCodes = {
    ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    INTERNAL_ERROR: 'INTERNAL_ERROR',
    UNAUTHORIZED: 'UNAUTHORIZED',

    DNPAY_ERROR: 'DNPAY_ERROR',
    APP_SESSION_EXPIRED: 'APP_SESSION_EXPIRED',
    INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',

    TOKEN_TRANSFER_FAILED: 'TOKEN_TRANSFER_FAILED',
    TREASURY_BALANCE_INSUFFICIENT: 'TREASURY_BALANCE_INSUFFICIENT',
};